Repository cordova-rtc/cordova-plugin-iosrtc, pull requests merged in 2019-09, with the labels that each got.

#374 Switch audio and video devices support
  dist/cordova-plugin-iosrtc.js
  js/getUserMedia.js
  package-lock.json
  src/PluginEnumerateDevices.swift
  src/PluginGetUserMedia.swift
  src/PluginRTCPeerConnection.swift
Labels: enhancement

#372 RTCPeerConnection.setLocalDescription() and other methods which take SDP as input now directly accept an object
  dist/cordova-plugin-iosrtc.js
  js/RTCPeerConnection.js
Labels: webrtc-api

#382 remove callback based API
  dist/cordova-plugin-iosrtc.js
  extra/renderer-and-libwebrtc-tests.js
  js/MediaDeviceInfo.js
  js/RTCPeerConnection.js
  js/enumerateDevices.js
  js/getUserMedia.js
Labels: enhancement, webrtc-api

#373 implement basic RTCPeerConnection.(getReceivers|getSenders|addTrack|removeTrack|addEventListener)
  .gitignore
  dist/cordova-plugin-iosrtc.js
  extra/renderer-and-libwebrtc-tests.js
  js/EventTarget.js
  js/MediaDeviceInfo.js
  js/MediaStream.js
  js/MediaStreamRenderer.js
  js/MediaStreamTrack.js
  js/RTCDTMFSender.js
  js/RTCDataChannel.js
  js/RTCPeerConnection.js
  js/enumerateDevices.js
  js/getUserMedia.js
  package-lock.json
  package.json
  src/PluginMediaStream.swift
  src/PluginRTCPeerConnection.swift
  src/iosrtcPlugin.swift
Labels: webrtc-api

#383 fix TypeError: undefined is not an object (evaluating 'stream.id') when removing stream
  extra/renderer-and-libwebrtc-tests.js
  src/PluginRTCPeerConnection.swift
Labels: bug
