Repository cordova-rtc/cordova-plugin-iosrtc, pull requests merged in 2019-10, with the labels that each got.

#393 Fix sdp in callback for addIceCandidate, and on icecandidate events
  src/PluginRTCPeerConnection.swift
Labels: bug

#395 Recognize when a video receives a new srcObject and re-render it
  dist/cordova-plugin-iosrtc.js
  js/videoElementsHandler.js
Labels: PluginMediaStreamRenderer, bug

#367 [Resolved] use safeAreaLayoutGuide for ios 11 and NSLayoutConstraint for ios 10 to fix elementView bad position depending status bar visibility
  src/PluginMediaStreamRenderer.swift
Labels: PluginMediaStreamRenderer, enhancement

#401 [WIP] attempt to implement RTCPeerConnection_RTCDTMFSender_insertDTMF without cordova-iosrtc patch for M54
  src/PluginRTCDTMFSender.swift
  src/PluginRTCPeerConnection.swift
  src/cordova-plugin-iosrtc-Bridging-Header.h
  src/iosrtcPlugin.swift
  src/webrtc-headers/WebRTC.h
Labels: libwebrtc

#402 Task/improve hook cycle
  .travis.yml
  docs/Building.md
  extra/hooks/iosrtc-swift-support.js
  plugin.xml
Labels: build, enhancement

#404 Restore Callbacks Support on registerGlobals getUserMedia|enumerateDevices RTCPeerConnection.prototype.createAnswer|createOffer|setRemoteDescription|setLocalDescription|addIceCandidate support for JsSIP, SIP.js and sipML5
  dist/cordova-plugin-iosrtc.js
  js/iosrtc.js
Labels: enhancement, external library support, getUserMedia

#405 Handle getUserMedia constraints mandatory / optional syntax that was …
  dist/cordova-plugin-iosrtc.js
  js/getUserMedia.js
Labels: webrtc-adapter

#406 implement peer optional proprietary constraints handling
  src/PluginRTCPeerConnectionConstraints.swift
Labels: enhancement, libwebrtc

#376 update travis build to use Xcode 11.0 (11A420a) and iOS 13 support
  .travis.yml
  README.md
  package.json
  plugin.xml
Labels: build

#413 Decode XML entities in project name in iosrtc-swift-support.js hook
  extra/hooks/iosrtc-swift-support.js
  package-lock.json
  package.json
Labels: bug, enhancement

#421 Task/ios arch
  .travis.yml
  docs/Building.md
  extra/ios_arch.js
Labels: build, documentation, enhancement

#416 implement RTCPeerConnectionFactory(encoderFactory, decoderFactory) using getSupportedVideoEncoder to enable VP8 and VP9
  src/iosrtcPlugin.swift
Labels: enhancement
