Repository cordova-rtc/cordova-plugin-iosrtc, pull requests merged in 2020-11, with the labels that each got.

#602 fix: PluginMediaStreamTrack.eventListener possible Fatal error: Unex…
  src/PluginMediaStreamTrack.swift
Labels: bug

#605 Fix MediaStreamTrack lifecycle and make GetStats logs silent.
  js/MediaStream.js
  js/RTCPeerConnection.js
  js/RTCStatsResponse.js
  src/PluginMediaStream.swift
  src/PluginMediaStreamTrack.swift
  src/PluginRTCPeerConnection.swift
  src/iosrtcPlugin.swift
Labels: bug, enhancement

#607 removed calling checkActive for connected local streams
  js/MediaStream.js
  js/RTCPeerConnection.js
  src/PluginRTCPeerConnection.swift
Labels: bug

#608 codestyle fixed
  src/PluginGetUserMedia.swift
  src/PluginMediaStream.swift
  src/PluginMediaStreamRenderer.swift
  src/PluginMediaStreamTrack.swift
  src/PluginRTCDTMFSender.swift
  src/PluginRTCDataChannel.swift
  src/PluginRTCPeerConnection.swift
  src/PluginRTCPeerConnectionConfig.swift
  src/PluginRTCPeerConnectionConstraints.swift
  src/PluginRTCVideoCaptureController.swift
  src/iosrtcPlugin.swift
Labels: enhancement

#609 fix plugin media stream renderer save leak
  js/iosrtc.js
  src/PluginMediaStreamRenderer.swift
  src/iosrtcPlugin.swift
  www/cordova-plugin-iosrtc.js
Labels: PluginMediaStreamRenderer, bug, enhancement
