Repository cordova-rtc/cordova-plugin-iosrtc, pull requests merged in 2020-10, with the labels that each got.

#587 refactor pluginMediaTracks lifecyle in PluginRTCPeerConnection, add canvas drawImage SHIM, add MediaStream(Track)?.clone
  js/MediaStream.js
  js/MediaStreamTrack.js
  js/RTCPeerConnection.js
  js/RTCRtpReceiver.js
  js/RTCRtpSender.js
  js/iosrtc.js
  src/PluginEnumerateDevices.swift
  src/PluginMediaStream.swift
  src/PluginMediaStreamTrack.swift
  src/PluginRTCPeerConnection.swift
  src/iosrtcPlugin.swift
  www/cordova-plugin-iosrtc.js
Labels: PluginMediaStreamRenderer, bug, enhancement, third party library support, webrtc-api

#586 feat: use background-color from video element css
  js/MediaStreamRenderer.js
  src/PluginMediaStreamRenderer.swift
  www/cordova-plugin-iosrtc.js
Labels: PluginMediaStreamRenderer, enhancement

#598 Prettier for JS styling
  .editorconfig
  .eslintrc
  .jshintrc
  .prettierrc
  .travis.yml
  extra/hooks/iosrtc-swift-support.js
  extra/ios-websocket-hack.js
  extra/ios_arch.js
  extra/renderer-and-libwebrtc-tests.js
  gulpfile.js
  js/Errors.js
  js/EventTarget.js
  js/MediaDevices.js
  js/MediaStream.js
  js/MediaStreamRenderer.js
  js/MediaStreamTrack.js
  js/RTCDTMFSender.js
  js/RTCDataChannel.js
  js/RTCIceCandidate.js
  js/RTCPeerConnection.js
  js/RTCRtpReceiver.js
  js/RTCRtpSender.js
  js/RTCRtpTransceiver.js
  js/RTCSessionDescription.js
  js/enumerateDevices.js
  js/getUserMedia.js
  js/iosrtc.js
  js/videoElementsHandler.js
  package-lock.json
  package.json
Labels: enhancement
