Repository cordova-rtc/cordova-plugin-iosrtc, pull requests merged in 2021-03, with the labels that each got.

#650 Issue #649 Media stream renderer unregister fix
  src/PluginMediaStreamRenderer.swift
Labels: PluginMediaStreamRenderer, bug, enhancement

#625 WIP: Task/589/implement addtransceiver
  js/MediaStream.js
  js/MediaStreamTrack.js
  js/RTCDataChannel.js
  js/RTCPeerConnection.js
  js/RTCRtpReceiver.js
  js/RTCRtpSender.js
  js/RTCRtpTransceiver.js
  js/iosrtc.js
  plugin.xml
  src/PluginRTCPeerConnection.swift
  src/PluginRTCRtpTransceiver.swift
  src/iosrtcPlugin.swift
  www/cordova-plugin-iosrtc.js
Labels: enhancement, webrtc-api

#664 extend transceiver/sender/receiver functionality
  js/RTCPeerConnection.js
  js/RTCRtpEncodingParameters.js
  js/RTCRtpReceiver.js
  js/RTCRtpSendParameters.js
  js/RTCRtpSender.js
  js/RTCRtpTransceiver.js
  js/RTCStatsReport.js
  plugin.xml
  src/PluginRTCPeerConnection.swift
  src/PluginRTCRtpCodecParameters.swift
  src/PluginRTCRtpEncodingParameters.swift
  src/PluginRTCRtpParameters.swift
  src/PluginRTCRtpReceiver.swift
  src/PluginRTCRtpSender.swift
  src/PluginRTCRtpTransceiver.swift
  src/cordova-plugin-iosrtc-Bridging-Header.h
  src/iosrtcPlugin.swift
  www/cordova-plugin-iosrtc.js
Labels: enhancement
